linters:
  enable-all: true

linters-settings:
  exhaustive:
    # indicates that switch statements are to be considered exhaustive if a
    # 'default' case is present, even if all enum members aren't listed in the
    # switch
    default-signifies-exhaustive: true
  errcheck:
    check-blank: true
    check-type-assertions: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - ifshort
