before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Tag}} -X main.Date={{.CommitDate}}
    mod_timestamp: '{{.CommitTimestamp}}'
archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "linux" }}Linux
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-snapshot-{{ .ShortCommit }}'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto

nfpms:
  -
    vendor: Arne Jørgensen
    maintainer: Arne Jørgensen <arne@arnested.dk>
    description: Local Docker Development DNS
    license: MIT
    formats:
      - deb
    dependencies:
      - avahi-daemon
      - docker.io | docker-ce
      - libsystemd0
    bindir: /usr/libexec
    changelog: ./changelog.yml
    contents:
      - src: systemd/ldddns.service
        dst: /lib/systemd/system/ldddns.service

      - src: deb/ldddns.sources
        dst: /etc/apt/sources.list.d/ldddns.sources

      - src: deb/ldddns.gpg
        dst: /usr/share/keyrings/ldddns.gpg

    scripts:
      postinstall: "deb/postinstall.sh"
      preremove: "deb/preremove.sh"
      postremove: "deb/postremove.sh"
