.TH LDDDNS 8 "" "" "Local Docker Development DNS"
.SH NAME
Local Docker Development DNS
.SH SYNOPSIS
.B systemctl
start ldddns

.B systemctl
status ldddns
.SH DESCRIPTION
A systemd service that will monitor your Docker host and provide DNS names for the containers.


.SH AUTHOR
Written by Arne Jørgensen - https://arnested.dk

.SH REPORTING BUGS
Report bugs to https://github.com/arnested/ldddns/issues

.SH COPYRIGHT
Copyright © 2020, 2021, 2022, 2023, 2024 Arne Jørgensen

Licensed under MIT License
